rewslies/config/routes.rb
Rewslies::Application.routes.draw do
  devise_for :users
  root "rewslies#index"

  resources :rewslies

end

rewslies/app/models/rewsly.rb
class Rewsly < ActiveRecord::Base
	validates :title, :link, :upvotes, :category, :presence => true
	validates :upvotes, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }

	def self.search_for ( query )
		Rewsly.where("title LIKE :query OR category LIKE :query",
			:query => "%#{query}%" )
	end
end

rewslies/app/controllers/rewslies_controller.rb
class RewsliesController < ApplicationController

	before_action :authenticate_user!, :only => [:new, :create]

	def index
		if params[:q].present?
			@rewlies = Rewsly.search_for(params[:q])
		else
			@rewlies = Rewsly.all
		end
	end

	def show
		@rewsly = Rewsly.find(params[:id])
	end

	def new
		@rewsly = Rewsly.new
	end

	def create
		@rewsly = Rewsly.new(safe_params)
		if	@rewsly.save
			redirect_to root_path
		else
			render :new
		end

	end

	private

	def safe_params
		return params.require(:rewsly).permit(:title, :link, :upvotes, :category)
	end
end

rewslies/app/helpers/rewslies_helper.rb
module RewsliesHelper
end

rewslies/app/views/rewslies/index.html.erb
<%= form_tag "/", :method => :get do %>
<%= text_field_tag :q, params[:q] %>
<%= submit_tag "Find me story" %>
<% end %>
<br> 

<p><a href="<%= new_rewsly_path %>">+Add New Story</a></p>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Upvotes</th>
			<th>Category</th>
		</tr>
	</thead>

	<tbody>
		<% @rewlies.each do |rewsly| %>
			<tr>
			<td><a href="<%= rewsly_path(rewsly) %>"><%= rewsly.title %></a></td>
			<td><%= rewsly.upvotes %></td>
			<td><%= rewsly.category %></td>
			</tr>
		<% end %>
	</tbody>
</table>

rewslies/app/views/rewslies/new.html.erb
<% if @rewsly.errors.any? %>
<h2>There were errors saving your news!</h2>
<ul>
	<% @rewsly.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>

<%= form_for @rewsly do |f| %>

	<div class="field">
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</div>

		<div class="field">
		<%= f.label :link %><br>
		<%= f.text_field :link %>
	</div>

	<div class="field">
		<%= f.label :upvotes %><br>
		<%= f.text_field :upvotes %>
	</div>

	<div class="field">
		<%= f.label :category %><br>
		<%= f.text_field :category %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

rewslies/app/views/rewslies/show.html.erb
<%= @rewsly.title %>
<br>
<a href="<%= @rewsly.link %>"%><%= @rewsly.link %></a>
<br>
<%= @rewsly.upvotes %>
<br>
<%= @rewsly.category %>