shirts/config/routes.rb
Shirts::Application.routes.draw do
  root "shirts#index"

  resources :shirts

end

shirts/app/models/shirt.rb
class Shirt < ActiveRecord::Base
	def self.search_for ( query )
		Shirt.where("name LIKE :query OR description LIKE :query", 
								:query => "%#{query}%")
	end
end

shirts/app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
	def index
		#query the database for all the rows in the shirts table
		#return items as array
		#use @shirts as variable

		#@shirts = Shirt.all
		if params[:q].present?
			@shirts = Shirt.search_for(params[:q])
		else
			@shirts = Shirt.all.order("created_at DESC")
		end
	end

	def show
		@shirt = Shirt.find(params[:id])
	end

	def new
		@shirt = Shirt.new
	end

	def create
		# params[:shirt] is a hash with all the fields for ths hirt object

		@shirt = Shirt.new( safe_shirt_params )
		logger.info ( @shirt.inspect )

		@shirt.save
		redirect_to root_path
	end
	
	def edit
		@shirt = Shirt.find(params[:id])
	end

	def update
		@shirt = Shirt.find(params[:id])
		@shirt.update( safe_shirt_params )

		redirect_to shirt_path(@shirt)
	end

	def destroy
		@shirt = Shirt.find(params[:id])
		@shirt.destroy

		redirect_to root_path
	end

	private

	def safe_shirt_params
		return params.require(:shirt).permit(:name, :description, :image)
	end

end

shirts/app/helpers/shirts_helper.rb
module ShirtsHelper
end

shirts/app/views/shirts/_form.html.erb
<%= form_for @shirt, :html => { :class => "form_class"} do |f| %>
	<div>
	<%= f.label :name, "Name of shirt", :class => "label_class" %><br>
	<%= f.text_field :name, :class => "text_field" %>
	</div>

	<div>
	<%= f.label :description, "Description" %><br>
	<%= f.text_field :description %>
	</div>

	<div>
	<%= f.label :image, "Image" %><br>
	<%= f.text_field :image %>
	</div>

	<%= f.submit "Create forms" %>

<% end %>

shirts/app/views/shirts/edit.html.erb
<h1>Editing a Shirt</h1>

<%= render "shirts/form" %>

shirts/app/views/shirts/index.html.erb
<a href = "%= root_path %"><h1>All the shirts!</h1></a>

<a href="<%= new_shirt_path %>">+ Add new shirt</a>
<br>
<br>

<%= form_tag "/", :method => :get do %>
	<%= text_field_tag :q, params[:q] %>
	<%= submit_tag "Find Me Shirts" %>
<% end %>

<ul>
	<% @shirts.each do |shirt| %>
	<li>
		<h2><a href="<%= shirt_path(shirt) %>"><%= shirt.name %></a></h2>
	</li>
		<p><%= shirt.description %></p>
		<img src="<%= image_path(shirt.image) %>">
	<% end %>
</ul>

shirts/app/views/shirts/new.html.erb
<h1>Add a shirt</h1>

<%= render "shirts/form" %>

shirts/app/views/shirts/show.html.erb
<h1><%= @shirt.name %></h1>
<a href="<%= edit_shirt_path ( @shirt ) %>">Edit Shirt</a>
<%= button_to "Delete Shirt", shirt_path(@shirt), :method => :delete %> 

<p><%= @shirt.description %></p>
<img src="<%= image_path( @shirt.image ) %>">