StuffFinders/config/routes.rb
StuffFinders::Application.routes.draw do
  devise_for :users
  root 'classifieds#index'

  resources :classifieds
  resources :categories
  

end

StuffFinders/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :classifieds
end

StuffFinders/app/models/classified.rb
class Classified < ActiveRecord::Base
	belongs_to :user
	belongs_to :category

	mount_uploader :image, ImageUploader
end

StuffFinders/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :classifieds
  has_many :categories
end

StuffFinders/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

StuffFinders/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end

	def show
		@classifieds = Classified.where(category_id="#{params[:id]}")
	end
end

StuffFinders/app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
	before_action :authenticate_user!, :only => [:new, :create]

	def index
		@classifieds = Classified.all
		@categories = Category.all
	end

	def new
		@classified = Classified.new
		@categories = Category.pluck(:name)
	end

	def create
		@classified = Classified.new(classified_params)
		@classified.user = current_user

		@category = params[:category]
		@classified.category = Category.where(:name => @category.capitalize).first_or_create

		@categories = Category.pluck(:name)

		    if @classified.save
                redirect_to root_path
            else 
                render :new
            end
	end

	def show
		@classified = Classified.find(params[:id])
	end

	def destroy
		@classified = Classified.find(params[:id])
		@classified.destroy

		redirect_to root_path
	end	

	def edit
		@classified = Classified.find(params[:id])
	end

	def update
		@classified = Classified.find(params[:id])
		@classified.update(classified_params)

		redirect_to root_path
	end

	private

	def classified_params
		params.require(:classified).permit(:category, :title, :description, :price, :image)
	end
end

StuffFinders/app/helpers/application_helper.rb
module ApplicationHelper
end

StuffFinders/app/helpers/categories_helper.rb
module CategoriesHelper
end

StuffFinders/app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

StuffFinders/app/views/categories/index.html.erb
<% @categories.each do |category| %>
	<a href="<%= category_path(category) %>"><%= category.name %></a><br>
<% end %>

StuffFinders/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuffFinders</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

<div class="navbar navbar-static-top">
    <div class="navbar-inner">
      <ul class="nav pull-right">
        <% if user_signed_in? %>
        <li><a href="#">Hi, <%= current_user.email %></a></li>
        <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
        <li><a href="<%= new_user_session_path %>">Log In</a></li>
        <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
        <% end %>
      </ul>
    </div>
  </div>


  <div class="navbar">
	  <div class="navbar-inner">
	    <a class="brand" href="<%= root_path %>">StuffFinder</a>
	    <ul class="nav">

	    	<li 
                <% if params[:controller] == "Classifieds" and params[:action] == "index" %> 
                class="active"
                <% end %>
                >
                <a href="<%= root_path %>">Browse Classifieds</a>
                </li>
                <li
                <% if params[:controller] == "Classifieds" and params[:action] == "new" %> 
                class="active"
                <% end %>
                >
                <a href="<%= new_classified_path %>">Post New Classified</a>
                </li>	      	
	    </ul>
	  </div>
   </div>

</head>
<body>
  <div class="container">
    <%= bootstrap_flash %>
    <%= yield %>
  </div>

</body>
</html>