games/config/routes.rb
Games::Application.routes.draw do
  root 'games#index'

  resources :games

  get 'about' => 'games#about'
  get 'how_it_works' => 'games#how_it_works'

  

end

games/app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
  
  def about
  end

  def how_it_works
  end
end

games/app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController
	def index
	end

	def show
		@user_pick = params[:id].to_i
		@computer_pick = rand(3) + 1
	end

end

games/app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
	def index
	end

	def show
		@chosen_number = params[:id].to_i
		@secret_number = rand(5) + 1
	end

end

games/app/helpers/games_helper.rb
module GamesHelper
end

games/app/helpers/rock_paper_scissors_helper.rb
module RockPaperScissorsHelper
end

games/app/helpers/secret_numbers_helper.rb
module SecretNumbersHelper
end

games/app/views/games/about.html.erb
<h1> About Me</h1>

<div class='span2'>
	<img src="<%= image_path("games/winner.gif") %>">
</div>

<div class='span10'>
	<p>Hi, my name is Ronny Hoesada</p>
	<p>I'm a BEWD student at General Assembly</p>
	<p>I'm learning to build rails apps</p>
	<p><a href="mailto:rhoesada@gmail.com">Email Me</a></p>
</div>

games/app/views/games/how_it_works.html.erb
<h1>How It Works</h1>

games/app/views/games/index.html.erb
<h1>Welcome to the Game Center!</h1>
<p>Choose a game below to get started</p>

<div class="row">
	<div class="span6">
		<div>
			<a href="<%= secret_numbers_path %>"><img src="<%= image_path("games/secret-number.jpg") %>"></a>
		</div>
		Secret Number
	</div>

	<div class="span6">
		<div>
			<a href="<%= rock_paper_scissors_path %>">
			<img src="<%= image_path("games/rock-paper-scissors.jpg") %>">
			</a>
		</div>
		Rock Paper Scissors
	</div>
</div>

games/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

    <div class="navbar">
    	<div class="navbar-inner">
    		<ul class="nav">
    			<li class="active"><a href='<%= root_path %>'>Games on Rails</a></li>
    			<li <% if params[:controller] == "main" and params[:action] == "about" %>
    				class="active"
    				<% end %>
    			>
    				<a href='<%= about_path %>'>About Us</a></li>
    			<li <% if params[:controller] == "main" and params[:action] == "how_it_works" %>
    				class="active"
    				<% end %>
    			>
    				<a href='<%= how_it_works_path %>'>How It Works</a></li>
    		</ul>
    	</div>
    </div>

	<%= yield %>

</div>

</body>
</html>

games/app/views/rock_paper_scissors/index.html.erb
<div class='container'>
	<h1>Welcome to Rock, Paper, Scissors Game</h1>

	<h4>Pick your weapon:</h4>

	<a href="<%= rock_paper_scissor_path( 1 ) %>">
	<img src="<%= image_path("rock_paper_scissors/rock.jpeg") %>">
	</a>

	<a href="<%= rock_paper_scissor_path( 2 ) %>">
	<img src="<%= image_path("rock_paper_scissors/paper.jpeg") %>">
	</a>

	<a href="<%= rock_paper_scissor_path( 3 ) %>">
	<img src="<%= image_path("rock_paper_scissors/scissors.jpeg") %>">
	</a>


</div>

games/app/views/rock_paper_scissors/show.html.erb
<div class='container'>

<div class='span2'>
	<a href="<%= rock_paper_scissors_path %>">Let's play again</a>
</div>

<div class='span8'>
	<% if @user_pick == @computer_pick %>
		<h1>It's a Tie</h1>
		<img src="<%= image_path("games/tie.jpg") %>">

	<% elsif @user_pick == 1 && @computer_pick == 3 %>
		<img src="<%= image_path("rock_paper_scissors/rock.jpeg") %>">
		<img src="<%= image_path("rock_paper_scissors/scissors.jpeg") %>">
	<h1>You win</h1>
		<img src="<%= image_path("games/winner.gif") %>">

	<% elsif @user_pick == 1 && @computer_pick == 2 %>
		<img src="<%= image_path("rock_paper_scissors/rock.jpeg") %>">
		<img src="<%= image_path("rock_paper_scissors/paper.jpeg") %>">
	<h1>You lose</h1>
		<img src="<%= image_path("games/cat-always-wins.jpeg") %>">
	
	<% elsif @user_pick == 2 && @computer_pick == 1 %>
		<img src="<%= image_path("rock_paper_scissors/paper.jpeg") %>">
		<img src="<%= image_path("rock_paper_scissors/rock.jpeg") %>">
	<h1>You win</h1>
		<img src="<%= image_path("games/winner.gif") %>">

	<% elsif @user_pick == 2 && @computer_pick == 3 %>
		<img src="<%= image_path("rock_paper_scissors/paper.jpeg") %>">
		<img src="<%= image_path("rock_paper_scissors/scissors.jpeg") %>">
	<h1>You lose</h1>
		<img src="<%= image_path("games/cat-always-wins.jpeg") %>">
	
	<% elsif @user_pick == 3 && @computer_pick == 1 %>
		<img src="<%= image_path("rock_paper_scissors/scissors.jpeg") %>">
		<img src="<%= image_path("rock_paper_scissors/rock.jpeg") %>">
	<h1>You lose</h1>
		<img src="<%= image_path("games/cat-always-wins.jpeg") %>">
	
	<% elsif @user_pick == 3 && @computer_pick == 2 %>
		<img src="<%= image_path("rock_paper_scissors/scissors.jpeg") %>">
		<img src="<%= image_path("rock_paper_scissors/paper.jpeg") %>">
	<h1>You win</h1>
		<img src="<%= image_path("games/winner.gif") %>">

	<% end %>
</div>
</div>